---
- name: Ensure PECL is installed
  apt: name={{item}} state=present
  with_items: 
  - php5
  - php-pear
  - build-essential
  - php5-dev

- name: Install PECL libaries.
  command: "pecl install {{ item }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  with_items: php_pecl_extensions